config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'
  get 'topics/error', to: 'topics#error', as: :error
  post 'topics/create', to: 'topics#create'
  post 'topics/destroy/:id', to: 'topics#destroy', as: :topic_destroy

  get '/show/:id', to: 'post#show', as: :post_show
  post '/posts/create', to: 'post#create', as: :post_create
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  validates :body, presence: true
end

app/models/tag_connect.rb
class TagConnect < ApplicationRecord
    belongs_to :tag_name
    belongs_to :topic
    validates :tag_name_id, presence: true
    validates :topic_id, presence: true
end

app/models/tag_name.rb
class TagName < ApplicationRecord
    has_many :topic, through: :tag_connect
    has_many :tag_connect, dependent: :destroy
    validates :name, uniqueness: true
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :post, dependent: :destroy
    has_many :tag_name, through: :tag_connect
    has_many :tag_connect, dependent: :destroy
    validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController

    def show
        @topic = Topic.find_by(id: params[:id])
        @post = Post.new(topic_id: params[:id])
        @posts = Post.where(topic_id: params[:id])
        tag = TagConnect.find_by(topic_id: params[:id])
        if tag
            @tags = TagName.where(id: tag.tag_name_id)
        end
    end

    def create
        if params[:post][:name].empty?
            params[:post][:name] = "名無しのフレンズ"
        end
        @post = Post.new(params[:post].permit(:topic_id, :name, :body))
        if @post.save
            redirect_to post_show_path(params[:post][:topic_id])
        else 
            id = params[:post][:topic_id].to_i 
            @topic = Topic.find(id) 
            @posts = Post.where(topic_id: id) 
            render :show 
        end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topic = Topic.new
    @t_name = TagName.new
    case
    when params[:search] 
      @topics = Topic.where('title LIKE(?)', "%#{params[:search]}%")
    when params[:t_search]
      @tag_name = TagName.find_by(name: params[:t_search])
      if @tag_name
        results = TagConnect.where(tag_name_id: @tag_name.id)
        n = []
        results.each { |result| n.push( result.topic_id ) }
        @topics = Topic.where("id IN (?)", n)
      else
        @topics = nil
      end
    else
      @topics = Topic.all
    end
  end

  def create 
    @topic = Topic.new(title: params[:title])
    if @topic.save
      if params[:t_name].present?
        @t_name = TagName.find_by(name: params[:t_name])
        if @t_name.nil?
          @t_name = TagName.new(name: params[:t_name])
          @t_name.save
        end
        @t_connect = TagConnect.new(topic_id: @topic.id, tag_name_id: @t_name.id)
        if @t_connect.save
          redirect_to root_path
          return
        else
          render error_path
          return
        end
      end
      redirect_to root_path
    else
      render error_path
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @tag = TagConnect.where(tag_name_id: params[:id])
    @post = Post.where(topic_id: params[:id])
    if @topic.destroy
      redirect_to root_path
    else
      render root_path
    end
  end

  def error
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BBSApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/show.html.erb
<h1><%= @topic.title %></h1>
<p>タグ</p>
<% if @tags %>
  <% @tags.each_with_index do |tag| %>
    <%= tag.name %></p>
  <% end %>
<% end %>
<hr>
<% @posts.each_with_index do |post , i| %>
  <p><%= i+1 %>:<%= post.name %></p>
  <p><%= post.body %></p>
<% end %>
<hr>
<%= link_to "戻る", root_path %>
<%= form_for @post, :url => post_create_path do |f| %>
  <p>
    <%= f.label :name, "名前" %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.text_area :body %>
  </p>

    <%= f.hidden_field :topic_id %>
  <p>
    <%= f.submit "投稿" %>
  </p>
<% end %>

app/views/topics/error.html.erb
<h1>エラー</h1>
<p>なんか間違ってます</p>

app/views/topics/index.html.erb
<h1>スレッド一覧</h1>
<%= form_tag root_path, method: :get do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "検索" %>
<% end %>
<p>タグ検索</p>
<%= form_tag root_path, method: :get do %>
  <%= text_field_tag :t_search, params[:t_search] %>
  <%= submit_tag "検索", name: nil %>
<% end %>

<% if @topics %>
  <ul>
    <% @topics.each_with_index do |topic, i| %>
      <li><%= i + 1 %>:<%= link_to topic.title, post_show_path(topic.id) %>
      <%= link_to '[削除]', topic_destroy_path(topic.id), method: :destroy, data: {confirm: "削除してもよろしいですか？"} %>

      </li>
    <% end %>
  </ul>
<% else %>
  <p>そのタグは存在しません</p>
<% end %>

<p>新規作成</p>
<%= form_tag topics_create_path do %>
    <%= label_tag :title, "スレッド名" %>
    <%= text_field_tag :title, @topic.title %>
    
    <%= label_tag :t_name, "タグ" %>
    <%= text_field_tag :t_name, @t_name.name %>

    <%= submit_tag %>
<% end %>